export const CONTRACT_TYPE = Object.freeze({ACQUISITION: 'ACQUISITION', SALE: 'SALE'});
export const CONTRACT_STATUS = Object.freeze({INTEREST: 'INTEREST', IN_PROGRESS: 'IN_PROGRESS', SIGNED: 'SIGNED'});
